[package]
name = "rsmd"
version = "1.30.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = {version = "*", optional = true}
nalgebra = "*"
ndarray = "0.15.6"
itertools = "0.12.1"
ndarray-rand = "=0.14.0"
googletest = "=0.2.0"

[features]
default = []
dev = ["clippy"]
