name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build in release mode with THP on
      run: MALLOC_CONF="thp:always,metadata_thp:always" cargo build --release
    - name: Run benchmark
      run: cargo bench
