name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run benchmark
      run: cargo bench
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
    - name: install matplotlib
      run: pip install matplotlib
    - name: plot Benchmark
      run: python3 plot.py
