name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with: 
          filename: .github/workflows/coverage.txt
          badge: true
