name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
    - name: Build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
